version: "3.9"
services:
  website:
    container_name: websitedev
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - "5000:5000"
    networks:
      - fullstack
    restart: on-failure
    volumes:
      - ./:/home/website
      - /home/website/node_modules
      - ./dist
networks:
  fullstack:
    driver: bridge
