name: "Deploy"

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install Packages
      run: npm install
    - name: Test
      run: npm run test
    - name: Deploy to GH Pages
      run: |
        git config --global user.email ${{ secrets.EMAIL }}
        git config --global user.name ${{ secrets.USERNAME }}
        git config --global github.token ${{ secrets.TOKEN }}
        git remote set-url origin https://github.com/KrzysztofZawisla/krzysztofzawisla.github.io
        npm run publish